# Chapter 04 — Practice Notebook

This notebook is my guided practice space for `ch04.ipynb`.

## How to use this notebook

For each example:

1. Read the original code.
2. Rewrite it in the `My version` cell using different values.
3. Run your version.
4. Explain what happened in `What I learned`.

The goal is not to copy code. The goal is to understand the concept and explain it clearly.

Original reference notebook: `../../_original/ch04.ipynb`


In [249]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1] if Path.cwd().name in {'notebooks', 'projects'} else Path.cwd()
DATASETS_DIR = PROJECT_ROOT / 'datasets'
EXAMPLES_DIR = PROJECT_ROOT / 'examples'
OUTPUTS_DIR = PROJECT_ROOT / 'book' / 'outputs'
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

PROJECT_ROOT, DATASETS_DIR, EXAMPLES_DIR, OUTPUTS_DIR


(PosixPath('/Users/luis/Desktop/PROYECTOS/Python-numpy-pandas/pydata-book'),
 PosixPath('/Users/luis/Desktop/PROYECTOS/Python-numpy-pandas/pydata-book/datasets'),
 PosixPath('/Users/luis/Desktop/PROYECTOS/Python-numpy-pandas/pydata-book/examples'),
 PosixPath('/Users/luis/Desktop/PROYECTOS/Python-numpy-pandas/pydata-book/book/outputs'))

## Example 01

### Original code

```python
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)
```

### What this example is about

Write the main idea here before running your own version.


In [250]:
# My version
# Rewrite the example here using your own values.
import matplotlib.pyplot as plt
import numpy as np

my_seed=np.random.seed(12345)
plt.rc("figure", figsize=(10,6))
np.set_printoptions(precision=4, suppress=True)


### What I learned

- 


## Example 02

### Original code

```python
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
```

### What this example is about

Write the main idea here before running your own version.


In [251]:
# My version
# Rewrite the example here using your own values.
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))




### What I learned

- 


## Example 03

### Original code

```python
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]
```

### What this example is about

Write the main idea here before running your own version.


In [252]:
# My version
# Rewrite the example here using your own values.
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

232 μs ± 1.45 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
12.1 ms ± 85.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### What I learned

- 


## Example 04

### Original code

```python
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data
```

### What this example is about

Write the main idea here before running your own version.


In [253]:
# My version
# Rewrite the example here using your own values.
import numpy as np

data= np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


### What I learned

- 


## Example 05

### Original code

```python
data * 10
data + data
```

### What this example is about

Write the main idea here before running your own version.


In [254]:
# My version
# Rewrite the example here using your own values.
result1 = data * 10,
result2 = data + data
print("resultado1:", result1)
print("resultado2:", result2)

resultado1: (array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]]),)
resultado2: [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


### What I learned

- 


## Example 06

### Original code

```python
data.shape
data.dtype
```

### What this example is about

Write the main idea here before running your own version.


In [255]:
# My version
# Rewrite the example here using your own values.
tamaño_dimension = data.shape
tipo_dato = data.dtype
print("tamaño de dimension:", tamaño_dimension)
print("tipo de dato:", tipo_dato)

tamaño de dimension: (2, 3)
tipo de dato: float64


### What I learned

- 


## Example 07

### Original code

```python
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1
```

### What this example is about

Write the main idea here before running your own version.


In [256]:
# My version
# Rewrite the example here using your own values.
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print("array to ndarray:", arr1)
print("type data:", arr1.dtype)


array to ndarray: [6.  7.5 8.  0.  1. ]
type data: float64


### What I learned

- 


## Example 08

### Original code

```python
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2
```

### What this example is about

Write the main idea here before running your own version.


In [257]:
# My version
# Rewrite the example here using your own values.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print("nuevo ndarray:", data2)
print("tamaño dimensiones:", arr2.shape)


nuevo ndarray: [[1, 2, 3, 4], [5, 6, 7, 8]]
tamaño dimensiones: (2, 4)


### What I learned

- 


## Example 09

### Original code

```python
arr2.ndim
arr2.shape
```

### What this example is about

Write the main idea here before running your own version.


In [258]:
# My version
# Rewrite the example here using your own values.
dimension_arr2 = arr2.ndim
tamaño_arr2 = arr2.shape
print("dimensiones presente:", dimension_arr2)
print("tamaño dimensiones:", tamaño_arr2)


dimensiones presente: 2
tamaño dimensiones: (2, 4)


### What I learned

- 


## Example 10

### Original code

```python
arr1.dtype
arr2.dtype
```

### What this example is about

Write the main idea here before running your own version.


In [259]:
# My version
# Rewrite the example here using your own values.
data_tipo = arr1.dtype
data_tipo_2 = arr2.dtype
print("tipo de dato:", data_tipo)
print("tipo de dato 2:", data_tipo_2)


tipo de dato: float64
tipo de dato 2: int64


### What I learned

- 


## Example 11

### Original code

```python
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))
```

### What this example is about

Write the main idea here before running your own version.


In [260]:
# My version
# Rewrite the example here using your own values.
ndarray_with_zeros = np.zeros(10)
ndarray_fila_colum = np.zeros((3,6))
print("ndarray with zeros:", ndarray_with_zeros, "ndarray with 3 fila and 6 column:", ndarray_fila_colum)


ndarray with zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ndarray with 3 fila and 6 column: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### What I learned

- 


## Example 12

### Original code

```python
np.arange(15)
```

### What this example is about

Write the main idea here before running your own version.


In [261]:
# My version
# Rewrite the example here using your own values.
array_14_elements = np.arange(15)
print("array de 14 elementos:", array_14_elements)

array de 14 elementos: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### What I learned

- 


## Example 13

### Original code

```python
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype
```

### What this example is about

Write the main idea here before running your own version.


In [262]:
# My version
# Rewrite the example here using your own values.
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print("asigned float64:", arr1)
print("asigned int32:", arr2)

asigned float64: [1. 2. 3.]
asigned int32: [1 2 3]


### What I learned

- 


## Example 14

### Original code

```python
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype
```

### What this example is about

Write the main idea here before running your own version.


In [263]:
# My version
# Rewrite the example here using your own values.
new_arr = np.array([1, 2, 3, 4, 5])
type_arr = new_arr.dtype
print("tipo dato:", type_arr)
float_arr = new_arr.astype(np.float64)
print("convert float:", float_arr)
print("tipe current:", float_arr)

tipo dato: int64
convert float: [1. 2. 3. 4. 5.]
tipe current: [1. 2. 3. 4. 5.]


### What I learned

- 


## Example 15

### Original code

```python
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)
```

### What this example is about

Write the main idea here before running your own version.


In [264]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print("array original:", arr)
result = arr.astype(np.int32)
print("convert to int 32:", result)


array original: [ 3.7 -1.2 -2.6  0.5 12.9 10.1]
convert to int 32: [ 3 -1 -2  0 12 10]


### What I learned

- 


## Example 16

### Original code

```python
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)
```

### What this example is about

Write the main idea here before running your own version.


In [265]:
# My version
# Rewrite the example here using your own values.
numeric_string = np.array(["1.5", "-9.6", "42"], dtype=np.bytes_)
print("array tipo string:", numeric_string)
numeric_string_to_float = numeric_string.astype(float)
print("Array string convert to float:", numeric_string_to_float)


array tipo string: [b'1.5' b'-9.6' b'42']
Array string convert to float: [ 1.5 -9.6 42. ]


### What I learned

- 


## Example 17

### Original code

```python
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)
```

### What this example is about

Write the main idea here before running your own version.


In [266]:
# My version
# Rewrite the example here using your own values.
int_array = np.arange(10)
print("array de 10 elementos:", int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50,], dtype=np.float64)
print("array in float 64:", calibers)
result = int_array.astype(calibers.dtype)
print("int to float , resultado:", result)

array de 10 elementos: [0 1 2 3 4 5 6 7 8 9]
array in float 64: [0.22  0.27  0.357 0.38  0.44  0.5  ]
int to float , resultado: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### What I learned

- 


## Example 18

### Original code

```python
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32
```

### What this example is about

Write the main idea here before running your own version.


In [267]:
# My version
# No representa numeros negativos, solo de 0 en adelante
zeros_uint32 = np.zeros(8, dtype="u4")
print(zeros_uint32)

[0 0 0 0 0 0 0 0]


### What I learned

- 


## Example 19

### Original code

```python
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr
```

### What this example is about

Write the main idea here before running your own version.


In [268]:
# My version
# [[1. 2. 3.]       [[1. 2. 3.]
# [4. 5. 6.]]   ×   [4. 5. 6.]]

#       ↓ elemento por elemento

# 1 × 1 = 1
# 2 × 2 = 4
# 3 × 3 = 9

# 4 × 4 = 16
# 5 × 5 = 25
# 6 × 6 = 36

arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
result_multiplication = arr * arr
print(result_multiplication)
result_rest = arr - arr
print(result_rest)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### What I learned

- 


## Example 20

### Original code

```python
1 / arr
arr ** 2
```

### What this example is about

Write the main idea here before running your own version.


In [269]:
# My version
# Rewrite the example here using your own values.
data = 1 / arr
print("resultado de la division:" ,data)
data1= arr **2
# 1² = 1
# 2² = 4
# 3² = 9

# 4² = 16
# 5² = 25
# 6² = 36
print("resultado de ** 2:", data1)

resultado de la division: [[1.     0.5    0.3333]
 [0.25   0.2    0.1667]]
resultado de ** 2: [[ 1.  4.  9.]
 [16. 25. 36.]]


### What I learned

- 


## Example 21

### Original code

```python
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr
```

### What this example is about

Write the main idea here before running your own version.


In [270]:
# My version
# Rewrite the example here using your own values.
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("ndarray:", arr2)
res = arr2 > arr 
print("array mayor que array:", res)


ndarray: [[ 0.  4.  1.]
 [ 7.  2. 12.]]
array mayor que array: [[False  True False]
 [ True False  True]]


### What I learned

- 


## Example 22

### Original code

```python
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr
```

### What this example is about

Write the main idea here before running your own version.


In [271]:
# My version
# Rewrite the example here using your own values.
arr = np.arange(10)
print(arr)
slice = arr[5:8]
print(slice)
new_valor = arr[5:8]= 12
print("new valor:", new_valor)


[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
new valor: 12


### What I learned

- 


## Example 23

### Original code

```python
arr_slice = arr[5:8]
arr_slice
```

### What this example is about

Write the main idea here before running your own version.


In [272]:
# My version
# Rewrite the example here using your own values.
arr_slice = arr[5:8]
print("slice:", arr_slice)

slice: [12 12 12]


### What I learned

- 


## Example 24

### Original code

```python
arr_slice[1] = 12345
arr
```

### What this example is about

Write the main idea here before running your own version.


In [273]:
# My version
# Rewrite the example here using your own values.
arr_slice[1] = 12345
print("renombrar data:", arr_slice)


renombrar data: [   12 12345    12]


### What I learned

- 


## Example 25

### Original code

```python
arr_slice[:] = 64
arr
```

### What this example is about

Write the main idea here before running your own version.


In [274]:
# My version
# Rewrite the example here using your own values.
arr_slice[:]= 64
print("asignar un valor a todo el array:", arr_slice)


asignar un valor a todo el array: [64 64 64]


### What I learned

- 


## Example 26

### Original code

```python
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
```

### What this example is about

Write the main idea here before running your own version.


In [275]:
# My version
# Rewrite the example here using your own values.
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
result = arr2d[2]
print("devuelve la posicion 2 del array:", result)


devuelve la posicion 2 del array: [7 8 9]


### What I learned

- 


## Example 27

### Original code

```python
arr2d[0][2]
arr2d[0, 2]
```

### What this example is about

Write the main idea here before running your own version.


In [276]:
# My version
# Rewrite the example here using your own values.
res = arr2d
print("array inicial:", res)
data1= arr2d[0][2]
print("extraer del array en posicion cero, el elemento en index 2:", data1)
data2 = arr2d[0, 2]
print("extrar del array en posicion cer, el elemento en index 2:", data2)

array inicial: [[1 2 3]
 [4 5 6]
 [7 8 9]]
extraer del array en posicion cero, el elemento en index 2: 3
extrar del array en posicion cer, el elemento en index 2: 3


### What I learned

- 


## Example 28

### Original code

```python
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
```

### What this example is about

Write the main idea here before running your own version.


In [277]:
# My version
# Rewrite the example here using your own values.
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("array  3 D:", arr3d)

array  3 D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### What I learned

- 


## Example 29

### Original code

```python
arr3d[0]
```

### What this example is about

Write the main idea here before running your own version.


In [278]:
# My version
# Rewrite the example here using your own values.
res = arr3d[0]
print("posicion cero de array  3 d:", res)

posicion cero de array  3 d: [[1 2 3]
 [4 5 6]]


### What I learned

- 


## Example 30

### Original code

```python
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d
```

### What this example is about

Write the main idea here before running your own version.


In [279]:
# My version
# Rewrite the example here using your own values.
res = arr3d
print("inicial array:", res)
old_values = arr3d[0].copy()
print("array copia:", old_values)

res1 = arr3d[0]= 42
print("reemplazar datos de la posicion 0 con 42:", res1)

arr = arr3d
print("array original:", arr)
arr3d[0]= old_values
print("reasignar valor:", arr3d)








inicial array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
array copia: [[1 2 3]
 [4 5 6]]
reemplazar datos de la posicion 0 con 42: 42
array original: [[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
reasignar valor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### What I learned

- 


## Example 31

### Original code

```python
arr3d[1, 0]
```

### What this example is about

Write the main idea here before running your own version.


In [280]:
# My version
# Rewrite the example here using your own values.
res0 = arr3d
print("original array:", res0)
res = arr3d[1, 0]
print("extraer data de lista index 1 y dentro la fila posicion 0:", res)

original array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
extraer data de lista index 1 y dentro la fila posicion 0: [7 8 9]


### What I learned

- 


## Example 32

### Original code

```python
x = arr3d[1]
x
x[0]
```

### What this example is about

Write the main idea here before running your own version.


In [281]:
# My version
# Rewrite the example here using your own values.
x = arr3d[1]
print("elementos de la posicion 1:", x)
data =x[0]
print("extraer datos de la lista en posicion 0:", data)


elementos de la posicion 1: [[ 7  8  9]
 [10 11 12]]
extraer datos de la lista en posicion 0: [7 8 9]


### What I learned

- 


## Example 33

### Original code

```python
arr
arr[1:6]
```

### What this example is about

Write the main idea here before running your own version.


In [282]:
# My version
# Rewrite the example here using your own values.
res = arr
print("original array:", res)

res1 = arr[1:6]
print("extraer datos desde index 1 al 6:", res1)

original array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
extraer datos desde index 1 al 6: [[[ 7  8  9]
  [10 11 12]]]


### What I learned

- 


## Example 34

### Original code

```python
arr2d
arr2d[:2]
```

### What this example is about

Write the main idea here before running your own version.


In [283]:
# My version
# Rewrite the example here using your own values.
data = arr2d
print("array inicial:", data)
data1 = arr2d[:2]
print("slice array:", data1)

array inicial: [[1 2 3]
 [4 5 6]
 [7 8 9]]
slice array: [[1 2 3]
 [4 5 6]]


### What I learned

- 


## Example 35

### Original code

```python
arr2d[:2, 1:]
```

### What this example is about

Write the main idea here before running your own version.


In [284]:
# My version
# Rewrite the example here using your own values.
array_parcial = arr2d[:2, 1:]
print("extrer array:", array_parcial)

extrer array: [[2 3]
 [5 6]]


### What I learned

- 


## Example 36

### Original code

```python
lower_dim_slice = arr2d[1, :2]
```

### What this example is about

Write the main idea here before running your own version.


In [285]:
# My version
# Rewrite the example here using your own values.
lower_dim_slice = arr2d[1, :2]
print("slice array:", lower_dim_slice)

slice array: [4 5]


### What I learned

- 


## Example 37

### Original code

```python
lower_dim_slice.shape
```

### What this example is about

Write the main idea here before running your own version.


In [286]:
# My version
# Rewrite the example here using your own values.
res0 = lower_dim_slice
print("original array:", res0)
res = lower_dim_slice.shape
print(res)


original array: [4 5]
(2,)


### What I learned

- 


## Example 38

### Original code

```python
arr2d[:2, 2]
```

### What this example is about

Write the main idea here before running your own version.


In [287]:
# My version
# Rewrite the example here using your own values.
res0= arr2d
print("array original:", res0)
res = arr2d[:2, 2]
print("extracion filas de 0 a 1, colum 2", res)

array original: [[1 2 3]
 [4 5 6]
 [7 8 9]]
extracion filas de 0 a 1, colum 2 [3 6]


### What I learned

- 


## Example 39

### Original code

```python
arr2d[:, :1]
```

### What this example is about

Write the main idea here before running your own version.


In [288]:
# My version
# Rewrite the example here using your own values.
data = arr2d[:, :1]
print("slice array:", data)

slice array: [[1]
 [4]
 [7]]


### What I learned

- 


## Example 40

### Original code

```python
arr2d[:2, 1:] = 0
arr2d
```

### What this example is about

Write the main idea here before running your own version.


In [289]:
# My version
# Rewrite the example here using your own values.
res = arr2d.copy()
print("original array:", res)
data = arr2d[:2, 1:] = 0
print("extraer las filas 0 y 1, desde columna 1 en adelante, y asignale el valor de 0", data)

original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
extraer las filas 0 y 1, desde columna 1 en adelante, y asignale el valor de 0 0


### What I learned

- 


## Example 41

### Original code

```python
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
names
data
```

### What this example is about

Write the main idea here before running your own version.


In [290]:
# My version
# Rewrite the example here using your own values.
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
print("array names:", names)
data = np.array([[4,7], [0,2], [-5, 6], [0,0], [1,2], [-12, -4], [3,4]])
print("data array:", data)

array names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data array: [[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


### What I learned

- 


## Example 42

### Original code

```python
names == "Bob"
```

### What this example is about

Write the main idea here before running your own version.


In [291]:
# My version
# Rewrite the example here using your own values.
isbob = names == "Bob"
print("is bob:", isbob)

is bob: [ True False False  True False False False]


### What I learned

- 


## Example 43

### Original code

```python
data[names == "Bob"]
```

### What this example is about

Write the main idea here before running your own version.


In [292]:
# My version
# Rewrite the example here using your own values.
var = data[names == "Bob"]
print("toma el indice en names donde aparece bob, devuelve una mascara [true, false...] y emparejalo con el mismo indice en data:", var)

toma el indice en names donde aparece bob, devuelve una mascara [true, false...] y emparejalo con el mismo indice en data: [[4 7]
 [0 0]]


### What I learned

- 


## Example 44

### Original code

```python
data[names == "Bob", 1:]
data[names == "Bob", 1]
```

### What this example is about

Write the main idea here before running your own version.


In [293]:
# My version
# Rewrite the example here using your own values.
res1 = data[names == "Bob", 1:] 
print("resultado, selecciona las filas donde el indice de bob es igual a data [[4,7], [0,0]], + la columna 1 hasta el final [[7],[0]]:", res1)
res2 = data[names == "Bob", 1]
print("resultado :", res2)

resultado, selecciona las filas donde el indice de bob es igual a data [[4,7], [0,0]], + la columna 1 hasta el final [[7],[0]]: [[7]
 [0]]
resultado : [7 0]


### What I learned

- 


## Example 45

### Original code

```python
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]
```

### What this example is about

Write the main idea here before running your own version.


In [294]:
# My version
# Rewrite the example here using your own values.
isDistint = names != "Bob" 

nameBob = ~(names == "Bob")
bobInData = data[~(names == "Bob")]

print("True donde el nombre NO es Bob:", isDistint)
print("negacion 2da version True donde el nombre NO es Bob:", nameBob)
print("Filas de data correspondientes a las posiciones "
    "donde names NO es Bob:", bobInData)




True donde el nombre NO es Bob: [False  True  True False  True  True  True]
negacion 2da version True donde el nombre NO es Bob: [False  True  True False  True  True  True]
Filas de data correspondientes a las posiciones donde names NO es Bob: [[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


### What I learned

- 


## Example 46

### Original code

```python
cond = names == "Bob"
data[~cond]
```

### What this example is about

Write the main idea here before running your own version.


In [295]:
# My version
# Rewrite the example here using your own values.
cond = names == "Bob"
print("es igual a bob (mascara booleana):", cond)

res = data[ ~ cond]
print("negando, o lo opuesto, de cond:", res)

es igual a bob (mascara booleana): [ True False False  True False False False]
negando, o lo opuesto, de cond: [[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


### What I learned

- 


## Example 47

### Original code

```python
mask = (names == "Bob") | (names == "Will")
mask
data[mask]
```

### What this example is about

Write the main idea here before running your own version.


## Example 47

### Original code

```python
mask = (names == "Bob") | (names == "Will")
mask
data[mask]
```

### What this example is about

Write the main idea here before running your own version.


In [297]:
# My version
# Rewrite the example here using your own values.
mask = (names == "Bob") | (names == "Will")
print("mascara bob o will:", mask)

mascara bob o will: [ True False  True  True  True False False]


### What I learned

- 


### What I learned

- 


## Example 48

### Original code

```python
data[data < 0] = 0
data
```

### What this example is about

Write the main idea here before running your own version.


In [300]:
x = data[data < 0] = 0
#True donde data tiene números menores que 0
#En todas las posiciones donde la máscara sea True, colocá 0.
print("initial data:", data)
print("resultado x:", x)



initial data: [[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]
resultado x: 0


### What I learned

- 


## Example 49

### Original code

```python
data[names != "Joe"] = 7
data
```

### What this example is about

Write the main idea here before running your own version.


In [301]:
a = data[names != "Joe"]
print("mostrar donde es distinto a Joe:", a)


mostrar donde es distinto a Joe: [[4 7]
 [0 6]
 [0 0]
 [1 2]]


### What I learned

- 


## Example 50

### Original code

```python
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr
```

### What this example is about

Write the main idea here before running your own version.


In [302]:
arr = np.zeros((8,4))
#En cada vuelta ocurre esto:
# i = 0 → arr[0] = 0
# i = 1 → arr[1] = 1
# i = 2 → arr[2] = 2
# ...
# i = 7 → arr[7] = 7

for i in range(8):
  arr[i] = i
print("resultado:", arr)


resultado: [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


### What I learned

- 


## Example 51

### Original code

```python
arr[[4, 3, 0, 6]]
```

### What this example is about

Write the main idea here before running your own version.


### What I learned

- 


## Example 52

### Original code

```python
arr[[-3, -5, -7]]
```

### What this example is about

Write the main idea here before running your own version.


In [173]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 53

### Original code

```python
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
```

### What this example is about

Write the main idea here before running your own version.


In [174]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 54

### Original code

```python
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
```

### What this example is about

Write the main idea here before running your own version.


In [175]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 55

### Original code

```python
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr
```

### What this example is about

Write the main idea here before running your own version.


In [176]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 56

### Original code

```python
arr = np.arange(15).reshape((3, 5))
arr
arr.T
```

### What this example is about

Write the main idea here before running your own version.


In [177]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 57

### Original code

```python
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)
```

### What this example is about

Write the main idea here before running your own version.


In [178]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 58

### Original code

```python
arr.T @ arr
```

### What this example is about

Write the main idea here before running your own version.


In [179]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 59

### Original code

```python
arr
arr.swapaxes(0, 1)
```

### What this example is about

Write the main idea here before running your own version.


In [180]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 60

### Original code

```python
samples = np.random.standard_normal(size=(4, 4))
samples
```

### What this example is about

Write the main idea here before running your own version.


In [181]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 61

### Original code

```python
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)
```

### What this example is about

Write the main idea here before running your own version.


In [182]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 62

### Original code

```python
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
```

### What this example is about

Write the main idea here before running your own version.


In [183]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 63

### Original code

```python
type(rng)
```

### What this example is about

Write the main idea here before running your own version.


In [184]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 64

### Original code

```python
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)
```

### What this example is about

Write the main idea here before running your own version.


In [185]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 65

### Original code

```python
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x
y
np.maximum(x, y)
```

### What this example is about

Write the main idea here before running your own version.


In [186]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 66

### Original code

```python
arr = rng.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part
```

### What this example is about

Write the main idea here before running your own version.


In [187]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 67

### Original code

```python
arr
out = np.zeros_like(arr)
np.add(arr, 1)
np.add(arr, 1, out=out)
out
```

### What this example is about

Write the main idea here before running your own version.


In [188]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 68

### Original code

```python
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys
```

### What this example is about

Write the main idea here before running your own version.


In [189]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 69

### Original code

```python
z = np.sqrt(xs ** 2 + ys ** 2)
z
```

### What this example is about

Write the main idea here before running your own version.


In [190]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 70

### Original code

```python
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
```

### What this example is about

Write the main idea here before running your own version.


In [191]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 71

### Original code

```python
plt.draw()
```

### What this example is about

Write the main idea here before running your own version.


In [192]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 72

### Original code

```python
plt.close("all")
```

### What this example is about

Write the main idea here before running your own version.


In [193]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 73

### Original code

```python
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
```

### What this example is about

Write the main idea here before running your own version.


In [194]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 74

### Original code

```python
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result
```

### What this example is about

Write the main idea here before running your own version.


In [195]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 75

### Original code

```python
result = np.where(cond, xarr, yarr)
result
```

### What this example is about

Write the main idea here before running your own version.


In [196]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 76

### Original code

```python
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)
```

### What this example is about

Write the main idea here before running your own version.


In [197]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 77

### Original code

```python
np.where(arr > 0, 2, arr) # set only positive values to 2
```

### What this example is about

Write the main idea here before running your own version.


In [198]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 78

### Original code

```python
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()
```

### What this example is about

Write the main idea here before running your own version.


In [199]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 79

### Original code

```python
arr.mean(axis=1)
arr.sum(axis=0)
```

### What this example is about

Write the main idea here before running your own version.


In [200]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 80

### Original code

```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()
```

### What this example is about

Write the main idea here before running your own version.


In [201]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 81

### Original code

```python
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
```

### What this example is about

Write the main idea here before running your own version.


In [202]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 82

### Original code

```python
arr.cumsum(axis=0)
arr.cumsum(axis=1)
```

### What this example is about

Write the main idea here before running your own version.


In [203]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 83

### Original code

```python
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values
```

### What this example is about

Write the main idea here before running your own version.


In [204]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 84

### Original code

```python
bools = np.array([False, False, True, False])
bools.any()
bools.all()
```

### What this example is about

Write the main idea here before running your own version.


In [205]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 85

### Original code

```python
arr = rng.standard_normal(6)
arr
arr.sort()
arr
```

### What this example is about

Write the main idea here before running your own version.


In [206]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 86

### Original code

```python
arr = rng.standard_normal((5, 3))
arr
```

### What this example is about

Write the main idea here before running your own version.


In [207]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 87

### Original code

```python
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr
```

### What this example is about

Write the main idea here before running your own version.


In [208]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 88

### Original code

```python
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2
```

### What this example is about

Write the main idea here before running your own version.


In [209]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 89

### Original code

```python
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)
```

### What this example is about

Write the main idea here before running your own version.


In [210]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 90

### Original code

```python
sorted(set(names))
```

### What this example is about

Write the main idea here before running your own version.


In [211]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 91

### Original code

```python
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])
```

### What this example is about

Write the main idea here before running your own version.


In [212]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 92

### Original code

```python
arr = np.arange(10)
np.save("some_array", arr)
```

### What this example is about

Write the main idea here before running your own version.


In [213]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 93

### Original code

```python
np.load("some_array.npy")
```

### What this example is about

Write the main idea here before running your own version.


In [214]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 94

### Original code

```python
np.savez("array_archive.npz", a=arr, b=arr)
```

### What this example is about

Write the main idea here before running your own version.


In [215]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 95

### Original code

```python
arch = np.load("array_archive.npz")
arch["b"]
```

### What this example is about

Write the main idea here before running your own version.


In [216]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 96

### Original code

```python
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)
```

### What this example is about

Write the main idea here before running your own version.


In [217]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 97

### Original code

```python
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz
```

### What this example is about

Write the main idea here before running your own version.


In [218]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 98

### Original code

```python
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)
```

### What this example is about

Write the main idea here before running your own version.


In [219]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 99

### Original code

```python
np.dot(x, y)
```

### What this example is about

Write the main idea here before running your own version.


In [220]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 100

### Original code

```python
x @ np.ones(3)
```

### What this example is about

Write the main idea here before running your own version.


In [221]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 101

### Original code

```python
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
mat @ inv(mat)
```

### What this example is about

Write the main idea here before running your own version.


In [222]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 102

### Original code

```python
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
```

### What this example is about

Write the main idea here before running your own version.


In [223]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 103

### Original code

```python
plt.figure()
```

### What this example is about

Write the main idea here before running your own version.


In [224]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 104

### Original code

```python
plt.plot(walk[:100])
```

### What this example is about

Write the main idea here before running your own version.


In [225]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 105

### Original code

```python
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()
```

### What this example is about

Write the main idea here before running your own version.


In [226]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 106

### Original code

```python
walk.min()
walk.max()
```

### What this example is about

Write the main idea here before running your own version.


In [227]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 107

### Original code

```python
(np.abs(walk) >= 10).argmax()
```

### What this example is about

Write the main idea here before running your own version.


In [228]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 108

### Original code

```python
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks
```

### What this example is about

Write the main idea here before running your own version.


In [229]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 109

### Original code

```python
walks.max()
walks.min()
```

### What this example is about

Write the main idea here before running your own version.


In [230]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 110

### Original code

```python
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30
```

### What this example is about

Write the main idea here before running your own version.


In [231]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 111

### Original code

```python
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times
```

### What this example is about

Write the main idea here before running your own version.


In [232]:
# My version
# Rewrite the example here using your own values.


### What I learned

- 


## Example 112

### Original code

```python
crossing_times.mean()
```

### What this example is about

Write the main idea here before running your own version.


In [233]:
# My version
# Rewrite the example here using your own values.
crossing_times = np.array([10, 20, 30, 40])
result = crossing_times.mean()
print("resultado:", result)

resultado: 25.0


### What I learned

- 


## Example 113

### Original code

```python
draws = 0.25 * rng.standard_normal((nwalks, nsteps))
```

### What this example is about

Write the main idea here before running your own version.


In [234]:
# My version
# Rewrite the example here using your own values.
rng = np.random.default_rng(seed=12345)

nwalks = 5000
nsteps = 1000

draws = 0.25 * rng.standard_normal((nwalks, nsteps))

steps = np.where(draws > 0, 1, -1)

walks = steps.cumsum(axis=1)

print(draws.shape)
print(steps.shape)
print(walks.shape)

(5000, 1000)
(5000, 1000)
(5000, 1000)


### What I learned

- 
